### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by danya201272** [LordTylus/SE-Torch-Plugin-ALE-ShipFixer#2]
Please add cooldown between copy and past is very fast,because server dont process

**Comment by LordTylus** [comment]
I dont quite understand the problem/request.

There is a cooldown for players so they are unable to spam the command. The cooldown is configurable.

Between the cut, and paste action of course there is no pause or waiting time. Because if there were time allowed to pass something could go there and occupy the space. 

for example the astronaut. maybe a block that starts falling down and what not, which wild start causing funny explosions.

The expensive action is pasting the grid back in. There however I read about how to make that a bit faster. Which I have not implemented yet.

**Comment by LordTylus** [comment]
@danya201272 any feedback? Otherwise Ill have to close the issue.

**Comment by LordTylus** [comment]
Closed because non responsive
