### ISSUE TITLE
Fixship changing enemy grid ownership

### ISSUE THREAD

**Issue by ShadowRS00** [LordTylus/SE-Torch-Plugin-ALE-ShipFixer#5]
Hi I've encountered an issue, when 2 grids from 2 different factions connect to each other via landing gear and then one player runs a !fixship on his grid to fix it, it will automatically change ownership on the connected grid as well without any of the plyers interacting with the ownership settings. It happens even though the grids belong to a completely different player from a different faction.
Steps to replicate:
1. Have 2 grids from 2 different players connected to each other via landing gear
2. Run a !fixship command on one of them while they are still connected together
3. This results in both grids belonging to the player who ran the !fixship command

**Comment by LordTylus** [comment]
Hello,

thank you for your report. 

Unfortunately I have been unable to reproduce the Issue you describe. Whenever you try to run !fixship and there is a ship in any way connected to it owned by a different player you get the following error message:

![image](https://user-images.githubusercontent.com/22499516/99115343-8a726c00-25f2-11eb-9bf5-3a9d14e04a5b.png)

Also there is not a single like on code in the entire plugin that changes the ownership of a the grid. Trying to force fix the ships using !fixshipmod cuts and pastes both and the ownership stays the same.

Do you run any mods or other plugins that could cause that behavior? Maybe something related to NPC Takeover or the like? When you are able to execute the !fixship command without being prevented from doing so something else must already have changed the ownership on it otherwise you would see the error message above. 

Have a nice evening

LordTylus

**Comment by LordTylus** [comment]
closed since cannot reproduce and unresponsive
